#!/bin/sh

DOCKER_BUILDX=$(docker buildx create --driver docker-container --use)
docker buildx build \
  --pull \
  --provenance=false \
  --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION:=8.5.0} \
  --build-arg ANSIBLE_LINT_VERSION=${ANSIBLE_LINT_VERSION:=6.20.3} \
  --build-arg BUILD_NAME="${CI_PROJECT_NAME}" \
  --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')" \
  --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}" \
  --platform=linux/arm64,linux/amd64 \
  -t ${IMAGE_NAME:=ansible-alpine:8.5.0} \
  .
docker buildx rm "${DOCKER_BUILDX}"
