#!/bin/sh
# $IMAGE_NAME var is injected into the build so the tag is correct.

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
             --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION} \
             --build-arg ANSIBLE_LINT_VERSION=${ANSIBLE_LINT_VERSION} \
             -t $IMAGE_NAME .
