#!/bin/bash

# Build hook for docker hub

if [ "${SOURCE_BRANCH}" = "master" ]; then
  VERSION=`tail -1 VERSION`
else
  VERSION=${SOURCE_BRANCH}
fi

docker build \
    --build-arg VERSION=${VERSION} \
    --build-arg VCS_REF=${SOURCE_COMMIT} \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    -t $IMAGE_NAME .
