#!/bin/sh

if [ "${SOURCE_BRANCH}" == "master" ]; then
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${ANSIBLE_VERSION}
    docker push $DOCKER_REPO:${ANSIBLE_VERSION}

    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:latest
    docker push ${DOCKER_REPO}:latest
fi
